"""Generate CLI wrapper scripts via PATH interception."""

import os
import stat
import subprocess

BIN_DIR = os.path.expanduser("~/.ip_guardian_bin")
ALLOWED_IPS_FILE = os.path.expanduser("~/.ip_guardian_allowed")

WRAPPER_SCRIPT = '''#!/bin/bash
# Auto-generated by IP Guardian. Do not edit.
REAL_CMD="{real_path}"
ALLOWED_SUBS=({allowed_subs})

# Allow whitelisted subcommands without IP check
for sub in "${{ALLOWED_SUBS[@]}}"; do
  if [ "$1" = "$sub" ]; then
    exec "$REAL_CMD" "$@"
  fi
done

current_ip=$(curl -s --max-time 5 ifconfig.me 2>/dev/null)
if [ -z "$current_ip" ]; then
  echo "\\033[33m[IP Guardian] Cannot check IP, {cmd} is blocked.\\033[0m"
  osascript -e 'display notification "Cannot check IP, {cmd} is blocked." with title "IP Guardian" subtitle "{cmd} blocked"' &
  exit 1
fi
if grep -qxF "$current_ip" ~/.ip_guardian_allowed 2>/dev/null; then
  exec "$REAL_CMD" "$@"
else
  echo "\\033[31m[IP Guardian] IP ($current_ip) not allowed, {cmd} is blocked.\\033[0m"
  osascript -e "display notification \\"IP ($current_ip) not allowed.\\" with title \\"IP Guardian\\" subtitle \\"{cmd} blocked\\"" &
  exit 1
fi
'''


def _find_real_path(cmd):
    """Find the real binary path, skipping our own wrapper."""
    # Search PATH excluding our bin dir
    env = os.environ.copy()
    paths = env.get("PATH", "").split(":")
    paths = [p for p in paths if p != BIN_DIR]
    env["PATH"] = ":".join(paths)
    try:
        result = subprocess.run(
            ["which", cmd], capture_output=True, text=True, env=env
        )
        return result.stdout.strip() or None
    except Exception:
        return None


def generate_wrappers(cli_commands, allowed_ips):
    """Generate wrapper scripts in ~/.ip_guardian_bin/."""
    write_allowed_ips(allowed_ips)
    os.makedirs(BIN_DIR, exist_ok=True)
    for entry in cli_commands:
        if isinstance(entry, str):
            cmd, allowed_subs = entry, []
        else:
            cmd = entry["cmd"]
            allowed_subs = entry.get("allowed_subcommands", [])
        real_path = _find_real_path(cmd)
        if not real_path:
            continue
        subs_str = " ".join(f'"{s}"' for s in allowed_subs)
        script = WRAPPER_SCRIPT.format(
            cmd=cmd, real_path=real_path, allowed_subs=subs_str
        )
        wrapper_path = os.path.join(BIN_DIR, cmd)
        with open(wrapper_path, "w") as f:
            f.write(script)
        os.chmod(wrapper_path, stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP)


def write_allowed_ips(allowed_ips):
    """Write allowed IPs to file for shell wrappers."""
    with open(ALLOWED_IPS_FILE, "w") as f:
        f.write("\n".join(allowed_ips) + "\n")


def get_path_line():
    """Return the line to add to .zshrc for PATH interception."""
    return f'\n# IP Guardian CLI protection\nexport PATH="{BIN_DIR}:$PATH"\n'
